version: "3.8"

services:
  notification-service:
    build: .
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_API_SECRET=${MAILJET_API_SECRET}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_NAME=${SENDER_NAME}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_QUEUE_NAME=book_notifications
      - NOTIFICATION_EMAIL=${NOTIFICATION_EMAIL}
    networks:
      - book-network
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Waiting for RabbitMQ...' &&
        while ! nc -z rabbitmq 5672; do sleep 1; done &&
        echo 'Starting notification service...' &&
        node server.js
      "
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3002/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  book-network:
    external: true
    name: book-network
